// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqtqdnxscegdivzkjdej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxdHFkbnhzY2VnZGl2emtqZGVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4Mzk1ODcsImV4cCI6MjA3MTQxNTU4N30.rUNreJUiWIhTFHvWqpL9H16vkydB3pKz_zRlv3cSYUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});